import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";

const projectDirectory = path.resolve(new URL("..", import.meta.url).pathname);

async function read(relativePath) {
  return fs.readFile(path.join(projectDirectory, relativePath), "utf8");
}

test("PDF text editor is exposed as a dedicated tool with history navigation", async () => {
  const route = await read("pages/pdf-text-editor.jsx");
  const shell = await read("components/pdf-text-editor.jsx");
  const navigation = await read("components/app-shell.jsx");
  const history = await read("components/tool-history.jsx");
  const comingSoon = await read("pages/coming-soon.jsx");
  assert.match(route, /PdfTextEditor/);
  assert.match(navigation, /href: "\/pdf-text-editor"/);
  assert.match(shell, /ToolViewTabs/);
  assert.match(shell, /ToolHistory tool="pdf-text-editor"/);
  assert.match(history, /"pdf-text-editor"/);
  assert.match(navigation, /label: "PDF editor"[^\n]+beta: true/);
  assert.match(navigation, /label: "PDF text editor"[^\n]+beta: true/);
  assert.match(navigation, /nav-beta/);
  const pdfEditorPosition = comingSoon.indexOf('["PDF editor"');
  const pdfTextEditorPosition = comingSoon.indexOf('["PDF text editor"');
  assert.ok(pdfEditorPosition >= 0 && pdfTextEditorPosition > pdfEditorPosition, "PDF text editor should follow PDF editor in Coming soon");
  assert.match(comingSoon, /\["PDF text editor"[^\n]+"Beta", "\/pdf-text-editor"\]/);
});

test("PDF text editor keeps browser mode disabled and submits identity-checked edits", async () => {
  const shell = await read("components/pdf-text-editor.jsx");
  const intake = await read("lib/job-intake.js");
  const worker = await read("worker/index.js");
  assert.match(shell, /Browser mode disabled/);
  assert.doesNotMatch(shell, /value="browser"/);
  assert.match(shell, /200 MB/);
  assert.match(shell, /originalTextHash/);
  assert.match(shell, /replacementText/);
  assert.match(shell, /Zoom out/);
  assert.match(shell, /Zoom in/);
  assert.match(shell, /Preview zoom/);
  assert.match(shell, /import\("\.\.\/lib\/pdf-text-preview\.js"\)/);
  assert.match(shell, /await Promise\.all\(pageModels\.map\(\(page\) => previewPdf\.getPage/);
  assert.match(shell, /setPreviewRevision\(\(current\) => current \+ 1\)/);
  assert.match(shell, /key=\{`\$\{model\.pageIndex\}-\$\{previewRevision\}`\}/);
  assert.match(shell, /sourceBytesRef\.current = data\.slice\(\)/);
  assert.match(shell, /\.\.\.operator,\s*pageIndex,/);
  assert.match(shell, /operatorOrdinal: run.ordinal/);
  assert.match(shell, /operatorOrdinals: run.operatorOrdinals/);
  assert.match(shell, /mergeVisualDuplicateRuns/);
  assert.match(shell, /mergeAdjacentTextRuns/);
  assert.match(shell, /operatorGroups/);
  assert.match(shell, /streamText.indexOf/);
  assert.doesNotMatch(shell, /if \(!item && textContent\.items\[itemCursor\]\) item =/);
  assert.match(shell, /Rebuilding the real PDF preview/);
  assert.match(shell, /applyRasterTextEdits/);
  assert.doesNotMatch(shell, /pdf-text-edit-preview/);
  assert.match(shell, /Continue editing/);
  assert.match(shell, /Keep final result on this device/);
  assert.match(shell, /Saved PDF name/);
  assert.match(shell, /Save to device/);
  assert.match(shell, /Exported PDFs are temporary unless you choose Save to device/);
  assert.match(shell, /form\.append\("filename"/);
  assert.match(intake, /outputFilename/);
  assert.match(worker, /safePdfOutputFilename\(options\.outputFilename/);
  assert.match(shell, /PdfTextJobLog logs=\{job\.logs \|\| \[\]\}/);
  assert.match(shell, /error\?\.code === "request_timeout"/);
  assert.match(shell, /takeHistoryEdit\("pdf-text-editor"\)/);
  assert.match(shell, /saved PDF could not be reopened/);
  assert.match(shell, /graphemeCount\(value\) > graphemeCount\(run\.text\)/);
  assert.match(await read("lib/pdf-text-preview.js"), /document.context.flateStream/);
  assert.match(await read("lib/pdf-text-preview.js"), /parseToUnicodeCMap/);
  assert.match(await read("lib/pdf-text-preview.js"), /embedded font code sequence/);
  assert.match(await read("lib/pdf-text-editor.js"), /NotoSansDevanagari/);
  assert.match(await read("lib/pdf-text-preview.js"), /embedPreviewFallbackFont/);
  assert.match(await read("lib/pdf-ocr-raster.js"), /expandedBox/);
  assert.match(await read("lib/pdf-ocr.js"), /applyRasterTextEdits/);
  assert.match(await read("lib/pdf-ocr.js"), /graphic: Boolean\(word\.graphic\)/);
  assert.match(shell, /devicePixelRatio/);
  assert.match(shell, /renderViewport/);
  assert.match(shell, /GlobalWorkerOptions\.workerSrc = "\/api\/pdf\/worker"/);
  assert.match(await read("styles/globals.css"), /\.pdf-text-page-frame \{[^}]*height: auto[^}]*overflow: visible/);
  assert.match(await read("styles/globals.css"), /\.pdf-text-page-frame \{[^}]*min-height: max\(/);
  assert.match(await read("styles/globals.css"), /\.pdf-text-page-surface \{[^}]*margin: 0 auto/);
  assert.match(shell, /const scale = .*previewZoom/);
  assert.match(shell, /surfaceSize/);
  assert.match(shell, /MAX_VIRTUAL_ITEMS = 50/);
  assert.match(shell, /useVirtualWindow/);
  assert.match(shell, /VirtualizedPdfTextPreview/);
  assert.match(shell, /VirtualizedPdfTextRail/);
  assert.match(shell, /scrollToIndex/);
  assert.match(shell, /onPointerDown=\{\(event\) => startTextDrag/);
  assert.match(shell, /const selectTextRun = \(run\) =>/);
  assert.match(shell, /onClick=\{\(\) => selectTextRun\(run\)\}/);
  assert.match(shell, /onMoveRunEnd/);
  assert.match(shell, /offsetX: offset\.x/);
  assert.match(shell, /textTransforms/);
  assert.match(shell, /const point = \[\.\.\.displayCenter\]/);
  assert.match(shell, /Util\.applyTransform\(point, inverse\)/);
  assert.match(shell, /scale: transform\.scale/);
  assert.match(shell, /rotation: transform\.rotation/);
  assert.match(shell, /onAppearanceChange/);
  assert.match(shell, /moveOnly/);
  assert.match(shell, /moveOnly: true/);
  assert.match(shell, /run\.graphic/);
  assert.match(shell, /Selected graphic/);
  assert.match(shell, /Automatic/);
  assert.match(shell, /chooseOcrMode\("auto"\)/);
  assert.match(shell, /requestedOcrMode === "auto"/);
  assert.match(shell, /Use OCR/);
  assert.match(shell, /Use embedded text only/);
  assert.match(shell, /chooseOcrMode\("ocr"\)/);
  assert.match(shell, /textReadModeLabel/);
  assert.match(shell, /pdf-text-selection-frame/);
  assert.match(shell, /pdf-text-rotation-handle/);
  assert.match(shell, /pdf-text-resize-handle/);
  assert.match(shell, /resizeHandleDirections/);
  assert.match(shell, /rasterPreviewTransforms/);
  assert.match(shell, /selectionHandlePoint/);
  assert.match(shell, /startDistance/);
  assert.match(shell, /onPreviewChange=\{previewTransform\}/);
  assert.match(shell, /setPointerCapture/);
  assert.match(shell, /event\.buttons & 1/);
  assert.match(shell, /onLostPointerCapture/);
  assert.match(shell, /shortestAngleDelta/);
  assert.match(shell, /isHorizontalSide/);
  assert.match(shell, /isVerticalSide/);
  assert.match(shell, /scale\(\$\{displayAppearance\.scaleX\}, \$\{displayAppearance\.scaleY\}\)/);
  assert.match(shell, /scaleX: transform\.scaleX/);
  assert.match(shell, /scaleY: transform\.scaleY/);
  assert.doesNotMatch(shell, /aria-label="Selected text rotation"/);
  assert.doesNotMatch(shell, /Rotate selected text counterclockwise/);
  assert.doesNotMatch(shell, /Rotate selected text clockwise/);
  assert.doesNotMatch(shell, /Decrease selected text size/);
  assert.doesNotMatch(shell, /Increase selected text size/);
  assert.doesNotMatch(shell, /Selected text size/);
  assert.doesNotMatch(shell, /pdf-text-appearance-controls/);
  assert.doesNotMatch(shell, /TextSelectionControls/);
  assert.doesNotMatch(shell, /pdf-text-selection-reset/);
  assert.doesNotMatch(await read("styles/globals.css"), /\.pdf-text-selection-controls/);
  assert.doesNotMatch(await read("styles/globals.css"), /\.pdf-text-selection-reset/);
  assert.match(await read("styles/globals.css"), /\.pdf-text-rotation-handle \{[^}]*touch-action: none/);
  assert.match(await read("styles/globals.css"), /\.pdf-text-resize-handle \{[^}]*touch-action: none/);
  assert.match(shell, /gesturechange/);
  assert.match(shell, /event\.preventDefault\(\)/);
  assert.doesNotMatch(shell, /pages\.map\(\(model\) => <PdfTextPage/);
  assert.doesNotMatch(shell, /pages\.map\(\(model\) => <PdfTextThumbnail/);
  const styles = await read("styles/globals.css");
  assert.match(styles, /\.pdf-text-run\.selected \{[^}]*z-index: 20/);
  assert.match(styles, /\.pdf-text-preview-scroll \{[^}]*display: block/);
  assert.match(styles, /\.pdf-text-preview-scroll \{[^}]*overscroll-behavior: auto/);
  assert.doesNotMatch(styles, /\.pdf-text-preview-scroll \{[^}]*overscroll-behavior: contain/);
  assert.match(styles, /\.pdf-text-preview-scroll \{[^}]*touch-action: pan-x pan-y/);
  assert.match(styles, /\.pdf-text-ocr-notice \{[^}]*margin: 15px 18px 15px/);
  assert.match(shell, /DismissibleMessage className="pdf-text-ocr-notice"/);
  assert.match(await read("components/dismissible-message.jsx"), /aria-label=\{ariaLabel\}/);
  assert.match(shell, /PDF_TEXT_THUMBNAIL_QUALITY = 1\.25/);
  assert.match(shell, /100 \* PDF_TEXT_THUMBNAIL_QUALITY/);
  assert.match(await read("components/pdf-editor.jsx"), /PDF_EDITOR_THUMBNAIL_QUALITY = 1\.25/);
  assert.match(styles, /\.pdf-text-run \{[^}]*cursor: grab/);
  assert.match(styles, /\.pdf-text-page-rail-scroll/);
  assert.match(styles, /\.pdf-text-virtual-item \{[^}]*justify-content: center/);
  assert.match(styles, /\.pdf-text-page \{[^}]*width: 100%/);
  assert.match(styles, /\.pdf-text-page-frame \{[^}]*margin-inline: auto/);
  assert.match(shell, /left: 0, width: "100%", height: `\$\{pageHeight\}px`/);
  assert.doesNotMatch(shell, /frameHeight \+ \(mobile \? 125 : 130\)/);
  assert.match(styles, /\.pdf-text-page-frame \{[^}]*justify-content: center/);
  assert.match(intake, /pdf-text-editor/);
  assert.match(intake, /operatorGroups/);
  assert.match(worker, /applyPdfTextEdits/);
  assert.match(shell, /inspectPdfWithOcr/);
  assert.match(shell, /requiresOcr/);
  assert.match(shell, /Running OCR on \$\{ocrPageIndexes.length\}/);
  assert.match(shell, /OCR on \$\{ocrPages\.map/);
  assert.match(shell, /Mixed text mode/);
  assert.match(shell, /Selected text · Page \{run\.pageIndex \+ 1\}/);
  assert.match(shell, /previewRequestRef/);
  assert.match(shell, /const sourceBytes = sourceBytesRef\.current\.slice\(\)/);
  assert.match(shell, /const pageModels = pages\.slice\(\)/);
  assert.match(shell, /An empty native edit list intentionally rebuilds from the source too/);
  assert.match(shell, /previewPagesByIndex = new Map\(pageModels\.map/);
  assert.match(shell, /hidden behind page artwork/);
  assert.match(shell, /OCR fallback/);
  assert.match(await read("components/processing-client.js"), /application\/x-ndjson/);
  assert.match(await read("components/processing-client.js"), /pageIndexes/);
  assert.match(await read("components/processing-client.js"), /response\.body\.getReader\(\)/);
  assert.match(await read("components/processing-client.js"), /agent_update_required/);
  assert.match(await read("components/processing-client.js"), /120 \* 1000/);
  assert.match(await read("components/processing-client.js"), /PDF OCR requires the latest Local Agent/);
  assert.match(shell, /capabilities\.pdf\?\.ocr !== true/);
  assert.match(await read("pages/api/pdf/ocr.js"), /type: "progress"/);
  assert.match(await read("agent/server.js"), /application\/x-ndjson/);
  assert.match(await read("lib/pdf-ocr.js"), /tesseract/);
  assert.match(await read("pages/api/pdf/ocr.js"), /recognizePdfText/);
  assert.match(await read("pages/api/pdf/ocr.js"), /pageIndexes/);
  assert.match(await read("agent/server.js"), /pageIndexes/);
  assert.match(worker, /without rasterizing/);
  assert.match(worker, /onProgress: reportReadProgress/);
  assert.match(await read("lib/pdf-text-editor.js"), /yieldToEventLoop/);
  assert.ok(shell.indexOf("Add one PDF") < shell.indexOf("pdf-text-editor-shell"), "the upload card should be above the preview shell");
});
