import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";

const projectDirectory = path.resolve(new URL("..", import.meta.url).pathname);

async function read(relativePath) {
  return fs.readFile(path.join(projectDirectory, relativePath), "utf8");
}

test("PDF text editor is exposed as a dedicated tool with history navigation", async () => {
  const route = await read("pages/pdf-text-editor.jsx");
  const shell = await read("components/pdf-text-editor.jsx");
  const navigation = await read("components/app-shell.jsx");
  const history = await read("components/tool-history.jsx");
  const comingSoon = await read("pages/coming-soon.jsx");
  assert.match(route, /PdfTextEditor/);
  assert.match(navigation, /href: "\/pdf-text-editor"/);
  assert.match(shell, /ToolViewTabs/);
  assert.match(shell, /ToolHistory tool="pdf-text-editor"/);
  assert.match(history, /"pdf-text-editor"/);
  assert.match(navigation, /label: "PDF editor"[^\n]+beta: true/);
  assert.match(navigation, /label: "PDF text editor"[^\n]+beta: true/);
  assert.match(navigation, /nav-beta/);
  assert.match(comingSoon, /\["PDF text editor"[^\n]+"Beta", "\/pdf-text-editor"\]/);
});

test("PDF text editor keeps browser mode disabled and submits identity-checked edits", async () => {
  const shell = await read("components/pdf-text-editor.jsx");
  const intake = await read("lib/job-intake.js");
  const worker = await read("worker/index.js");
  assert.match(shell, /Browser mode disabled/);
  assert.doesNotMatch(shell, /value="browser"/);
  assert.match(shell, /200 MB/);
  assert.match(shell, /originalTextHash/);
  assert.match(shell, /replacementText/);
  assert.match(shell, /Zoom out/);
  assert.match(shell, /Zoom in/);
  assert.match(shell, /Preview zoom/);
  assert.match(shell, /import\("\.\.\/lib\/pdf-text-preview\.js"\)/);
  assert.match(shell, /await Promise\.all\(pages\.map\(\(page\) => previewPdf\.getPage/);
  assert.match(shell, /setPreviewRevision\(\(current\) => current \+ 1\)/);
  assert.match(shell, /key=\{`\$\{model\.pageIndex\}-\$\{previewRevision\}`\}/);
  assert.match(shell, /sourceBytesRef\.current = data\.slice\(\)/);
  assert.match(shell, /\.\.\.operator,\s*pageIndex,/);
  assert.match(shell, /operatorOrdinal: run.ordinal/);
  assert.match(shell, /operatorOrdinals: run.operatorOrdinals/);
  assert.match(shell, /mergeVisualDuplicateRuns/);
  assert.match(shell, /operatorGroups/);
  assert.match(shell, /streamText.indexOf/);
  assert.doesNotMatch(shell, /if \(!item && textContent\.items\[itemCursor\]\) item =/);
  assert.match(shell, /Rebuilding the real PDF preview/);
  assert.match(shell, /applyRasterTextEdits/);
  assert.doesNotMatch(shell, /pdf-text-edit-preview/);
  assert.match(shell, /Continue editing/);
  assert.match(await read("lib/pdf-text-preview.js"), /document.context.flateStream/);
  assert.match(await read("lib/pdf-ocr-raster.js"), /expandedBox/);
  assert.match(await read("lib/pdf-ocr.js"), /applyRasterTextEdits/);
  assert.match(shell, /devicePixelRatio/);
  assert.match(shell, /renderViewport/);
  assert.match(shell, /GlobalWorkerOptions\.workerSrc = "\/api\/pdf\/worker"/);
  assert.match(await read("styles/globals.css"), /\.pdf-text-page-frame \{[^}]*overflow: auto/);
  assert.match(await read("styles/globals.css"), /\.pdf-text-page-surface \{[^}]*margin: 0 auto/);
  assert.match(shell, /const scale = .*previewZoom/);
  assert.match(shell, /surfaceSize/);
  assert.match(shell, /MAX_VIRTUAL_ITEMS = 50/);
  assert.match(shell, /useVirtualWindow/);
  assert.match(shell, /VirtualizedPdfTextPreview/);
  assert.match(shell, /VirtualizedPdfTextRail/);
  assert.match(shell, /scrollToIndex/);
  assert.doesNotMatch(shell, /pages\.map\(\(model\) => <PdfTextPage/);
  assert.doesNotMatch(shell, /pages\.map\(\(model\) => <PdfTextThumbnail/);
  const styles = await read("styles/globals.css");
  assert.match(styles, /\.pdf-text-run\.selected \{[^}]*z-index: 20/);
  assert.match(styles, /\.pdf-text-preview-scroll \{[^}]*display: block/);
  assert.match(styles, /\.pdf-text-page-rail-scroll/);
  assert.match(styles, /\.pdf-text-virtual-item \{[^}]*justify-content: center/);
  assert.match(styles, /\.pdf-text-page-frame \{[^}]*justify-content: center/);
  assert.match(intake, /pdf-text-editor/);
  assert.match(intake, /operatorGroups/);
  assert.match(worker, /applyPdfTextEdits/);
  assert.match(shell, /inspectPdfWithOcr/);
  assert.match(shell, /requiresOcr/);
  assert.match(shell, /Running OCR on \$\{ocrPageIndexes.length\}/);
  assert.match(shell, /OCR on \$\{ocrPages\.map/);
  assert.match(shell, /Mixed text mode/);
  assert.match(shell, /Selected text · Page \{run\.pageIndex \+ 1\}/);
  assert.match(shell, /previewRequestRef/);
  assert.match(shell, /previewPagesByIndex = new Map\(pages\.map/);
  assert.match(shell, /hidden behind page artwork/);
  assert.match(shell, /OCR fallback/);
  assert.match(await read("components/processing-client.js"), /application\/x-ndjson/);
  assert.match(await read("components/processing-client.js"), /pageIndexes/);
  assert.match(await read("components/processing-client.js"), /response\.body\.getReader\(\)/);
  assert.match(await read("components/processing-client.js"), /agent_update_required/);
  assert.match(await read("components/processing-client.js"), /PDF OCR requires the latest Local Agent/);
  assert.match(shell, /capabilities\.pdf\?\.ocr !== true/);
  assert.match(await read("pages/api/pdf/ocr.js"), /type: "progress"/);
  assert.match(await read("agent/server.js"), /application\/x-ndjson/);
  assert.match(await read("lib/pdf-ocr.js"), /tesseract/);
  assert.match(await read("pages/api/pdf/ocr.js"), /recognizePdfText/);
  assert.match(await read("pages/api/pdf/ocr.js"), /pageIndexes/);
  assert.match(await read("agent/server.js"), /pageIndexes/);
  assert.match(worker, /without rasterizing/);
  assert.ok(shell.indexOf("Add one PDF") < shell.indexOf("pdf-text-editor-shell"), "the upload card should be above the preview shell");
});
