import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";

const projectDirectory = path.resolve(new URL("..", import.meta.url).pathname);

async function read(relativePath) {
  return fs.readFile(path.join(projectDirectory, relativePath), "utf8");
}

test("PDF editor renders full previews at high resolution while keeping thumbnails small", async () => {
  const shell = await read("components/pdf-editor.jsx");
  const previewRoute = await read("pages/api/pdf/preview.js");
  const workerRoute = await read("pages/api/pdf/worker.js");
  const licenseClient = await read("components/license-client.js");
  const licenseProxy = await read("pages/api/license/[...path].js");
  const styles = await read("styles/globals.css");
  assert.match(shell, /const pixelRatio = Math\.min\(3, Math\.max\(2,/);
  assert.match(shell, /const renderViewport = pageInfo\.pdfPage\.getViewport\(\{ scale: scale \* pixelRatio, rotation \}\)/);
  assert.match(shell, /canvas\.style\.width = "100%"/);
  assert.match(previewRoute, /request\.query\.thumbnail === "1" \? "40" : "180"/);
  assert.match(shell, /GlobalWorkerOptions\.workerSrc = "\/api\/pdf\/worker"/);
  assert.match(shell, /previewViewportLimits/);
  assert.match(shell, /calculatePreviewPageLayout/);
  assert.match(shell, /const scale = layout\.scale/);
  assert.match(shell, /data-preview-zoomed/);
  assert.match(styles, /\.pdf-page-canvas-wrap \{[^}]*height: auto[^}]*min-height: 0[^}]*overflow: auto/);
  assert.match(styles, /\.pdf-page-canvas-wrap\[data-preview-zoomed="false"\] \.pdf-page-canvas-surface/);
  assert.match(shell, /surfaceSize/);
  assert.match(shell, /imagePreviewStyle\(page, image, placement\)/);
  assert.match(shell, /rotation: normalizeImageRotation\(image\.rotation\)/);
  assert.match(shell, /ObjectTransformHandles/);
  assert.match(shell, /selectedImageId/);
  assert.match(shell, /selectedTextBoxId/);
  assert.match(shell, /selectedObject\?\.pageId === page\.id/);
  assert.match(shell, /pdf-object-resize-handle/);
  assert.match(shell, /pdf-object-rotation-handle/);
  assert.match(styles, /\.pdf-image-overlay\.selected/);
  assert.match(styles, /\.pdf-text-box-overlay\.selected/);
  assert.match(styles, /\.pdf-object-transform-handles/);
  assert.match(styles, /\.text-box-remove-handle \{[^}]*z-index: 4[^}]*top: -31px[^}]*left: -8px/);
  assert.match(styles, /\.image-remove-handle \{[^}]*z-index: 4[^}]*top: -31px[^}]*left: -8px/);
  assert.match(styles, /\.processing-format-table thead th:first-child \{ width: 28%; \}/);
  assert.match(styles, /\.processing-format-table tbody th \{[^}]*white-space: normal;[^}]*overflow-wrap: anywhere;/);
  assert.match(shell, /Text box/);
  assert.doesNotMatch(shell, /<button className="secondary-button" type="button" onClick=\{addTextBox\} disabled=\{!selectedPage\}/);
  assert.match(shell, /Text size for text box/);
  assert.match(shell, /Background color for text box/);
  assert.match(shell, /onChangeTextBoxes/);
  assert.match(shell, /setSelectedObject\(\{ type: "textBox", id: textBox\.id, pageId: selectedPage\.id \}\)/);
  assert.match(shell, /History/);
  assert.match(shell, /undoDocument/);
  assert.match(shell, /redoDocument/);
  assert.match(shell, /history === "coalesce"/);
  assert.doesNotMatch(shell, /pdf-shortcuts/);
  assert.match(shell, /Delete page/);
  assert.match(shell, /Drop here/);
  assert.match(shell, /onDragStart=\{\(event\) => startDraggingPage\(page\.id, event\)\}/);
  assert.match(shell, /onDrag=\{handlePageDrag\}/);
  assert.match(shell, /nativeDraggable=\{!mobileLayout\}/);
  assert.match(shell, /draggable=\{nativeDraggable\}/);
  assert.match(shell, /window\.matchMedia\("\(max-width: 680px\)"\)/);
  assert.match(shell, /pointerPageScrollRef/);
  assert.match(shell, /handlePageListPointerMove/);
  assert.match(shell, /list\.scrollLeft -= event\.clientX - scroll\.lastX/);
  assert.match(shell, /const handlePageListWheel = \(event\) =>/);
  assert.match(shell, /onWheel=\{handlePageListWheel\}/);
  assert.match(shell, /event\.shiftKey \? \(event\.deltaY \|\| event\.deltaX\) : Math\.abs\(event\.deltaX\) > Math\.abs\(event\.deltaY\) \? event\.deltaX : 0/);
  assert.match(shell, /event\.currentTarget\.setPointerCapture\?\.\(event\.pointerId\)/);
  assert.match(shell, /className="thumbnail-page-image"[^>]*draggable="false"/);
  assert.match(shell, /className="thumbnail-image-overlay"[\s\S]*?draggable="false"/);
  assert.match(shell, /function PdfPageThumbnail\([\s\S]*?onDrag, onDragEnd/);
  assert.match(shell, /emits drag events, so keep the auto-scroll pointer position fresh here/);
  assert.match(shell, /Keep the loop alive while a drag is active/);
  assert.match(shell, /pointerPageDragRef\.current\?\.active\) updatePointerPageDrop/);
  assert.match(shell, /const pageDropPosition = \(event, element\) =>/);
  assert.match(shell, /list\.scrollWidth > list\.clientWidth \+ 1 && list\.scrollHeight <= list\.clientHeight \+ 1/);
  assert.match(shell, /event\.clientX < bounds\.left \+ bounds\.width \/ 2/);
  assert.match(shell, /pointerPageDragRef/);
  assert.match(shell, /findPageAtPointer/);
  assert.match(shell, /onPointerDown=\{\(event\) => handlePagePointerDown\(event, page\.id\)\}/);
  assert.match(shell, /thumbnail-drag-handle/);
  assert.match(styles, /\.thumbnail-drag-handle \{[^}]*touch-action: none/);
  assert.match(styles, /\.pdf-page-list \{[^}]*touch-action: pan-x/);
  assert.match(styles, /\.pdf-page-list \{[^}]*width: 100%; min-width: 0/);
  assert.match(styles, /\.pdf-page-rail \{[^}]*align-self: stretch; width: 100%/);
  assert.match(styles, /\.pdf-page-thumbnail \{[^}]*touch-action: pan-x/);
  assert.match(styles, /\.pdf-page-thumbnail \{[^}]*-webkit-user-drag: none/);
  assert.match(shell, /contentEditable/);
  assert.match(shell, /selection.start < 0 \|\| selection.end < selection.start/);
  assert.match(shell, /restoreTextSelection\(editor, selection\)/);
  assert.match(shell, /applyTextBoxRangeStyle/);
  assert.match(shell, /runs: Array\.isArray\(textBox\.runs\)/);
  assert.match(await read("lib/pdf-text-box.js"), /Roboto/);
  assert.match(await read("lib/pdf-text-box.js"), /NotoSansDevanagari/);
  assert.match(await read("lib/pdf-text-box.js"), /layoutPdfTextRuns/);
  assert.match(await read("styles/globals.css"), /roboto-regular\.ttf/);
  assert.match(await read("styles/globals.css"), /noto-sans-devanagari-regular\.ttf/);
  assert.match(shell, /images\.length \? <ImageOverlayLayer[\s\S]*?textBoxes\.length \? null : <button className="blank-page-message"/);
  assert.doesNotMatch(shell, /Keep final result on this device/);
  assert.doesNotMatch(shell, /keepResultTouchedRef/);
  assert.doesNotMatch(shell, /pdf-retention-info/);
  assert.match(shell, /const effectiveKeepResult = processingMode === "local" && saveToDevice/);
  assert.match(shell, /resultFilenameStem/);
  assert.match(shell, /form\.append\("filename"/);
  assert.match(shell, /Saved PDF name/);
  assert.match(shell, /Save to device/);
  assert.ok(shell.indexOf('className="pdf-retention-row"') < shell.indexOf('className={`pdf-editor-toolbar'), "the saved-file row should precede the PDF tools row");
  assert.match(styles, /\.pdf-more-tools-menu \{[^}]*z-index: 1000/);
  assert.match(styles, /\.pdf-more-tools \{[^}]*z-index: 2/);
  assert.match(await read("lib/job-intake.js"), /safePdfOutputFilename/);
  assert.match(await read("worker/index.js"), /manifest\.outputFilename/);
  assert.match(styles, /\.pdf-editor-shell \{[^}]*overflow: hidden/);
  assert.match(styles, /\.pdf-retention-row \{/);
  assert.match(styles, /\.pdf-retention-row \{[^}]*z-index: 1/);
  assert.match(workerRoute, /path\.join\(process\.cwd\(\), "node_modules", "pdfjs-dist"/);
  assert.match(licenseClient, /LICENSE_PROXY_URL = "\/api\/license"/);
  assert.match(licenseClient, /direct Funnel URL/);
  assert.match(licenseProxy, /bodyParser: false/);
  assert.match(licenseProxy, /MAX_UPSTREAM_ATTEMPTS = 2/);
  assert.match(licenseProxy, /requestOverIpv4/);
  assert.match(licenseProxy, /dns\.resolve4/);
  assert.match(licenseProxy, /lookupOptions\?\.all/);
  assert.match(licenseProxy, /family: 4/);
  assert.match(licenseProxy, /The licensing server request timed out/);
});

test("PDF editor can export blank-page-only projects and lets users rename downloads", async () => {
  const shell = await read("components/pdf-editor.jsx");
  const intake = await read("lib/job-intake.js");
  const worker = await read("worker/index.js");
  const filenameField = await read("components/result-filename.jsx");
  assert.match(shell, /Start with blank page/);
  assert.match(shell, /pages\.some\(\(page\) => page\?\.kind === "source"/);
  assert.doesNotMatch(intake, /if \(pdfFiles\.length < 1\) throw new Error\("Add at least one PDF\."\)/);
  assert.match(worker, /manifest\.pdfs\.length > 1 \? "merged" : "blank_pages"/);
  assert.match(await read("scripts/stage-agent-package.mjs"), /staged Local agent still contains the old PDF-editor requirement/);
  assert.match(filenameField, /Download file name/);
  assert.match(shell, /Save to device/);
  assert.match(shell, /const effectiveKeepResult = processingMode === "local" && saveToDevice/);
  assert.match(await read("components/tool-page.jsx"), /ResultFilenameField/);
  assert.match(await read("components/pdf-text-editor.jsx"), /ResultFilenameField/);
  assert.match(worker, /layoutPdfTextRuns/);
  assert.match(intake, /styled range/);
});

test("PDF editor keeps advanced editing Local-agent-only in Browser mode", async () => {
  const shell = await read("components/pdf-editor.jsx");
  const options = await read("components/processing-options.jsx");
  const browserProcessing = await read("components/browser-processing.js");
  assert.match(browserProcessing, /BROWSER_PDF_EDITOR_IMAGE_MAX_BYTES = 1 \* 1024 \* 1024/);
  assert.match(browserProcessing, /BROWSER_PDF_EDITOR_MAX_TOTAL_BYTES = 50 \* 1024 \* 1024/);
  assert.match(browserProcessing, /"pdf-editor"/);
  assert.match(shell, /BROWSER_TEXT_BOX_ERROR = "Styled text boxes require Local agent\. Switch to Local agent to continue\."/);
  assert.match(shell, /BROWSER_DUPLICATE_PAGE_ERROR = "Duplicating pages requires Local agent\. Switch to Local agent to continue\."/);
  assert.match(shell, /BROWSER_PASSWORD_PDF_ERROR = "Password-protected PDFs require Local agent\. Switch to Local agent to continue\."/);
  assert.match(shell, /BROWSER_IMAGE_FORMAT_ERROR = "Browser mode accepts PNG, JPG, and JPEG images only\. Use Local agent for other formats\."/);
  assert.match(shell, /BROWSER_IMAGE_SIZE_ERROR = "Browser mode accepts images up to 1 MB each\. Use Local agent for larger images\."/);
  assert.match(shell, /BROWSER_PROJECT_ERROR = "This project contains a Local-agent-only feature\. Switch to Local agent to export it\."/);
  assert.match(shell, /function PdfJobCard\(\{ job: initialJob, mode = "local"[\s\S]*?useEffect\(\(\) => \{\s*if \(mode === "browser"\) return undefined;/);
  assert.match(shell, /processingMode === "browser"/);
  assert.match(shell, /browserPdfProjectError/);
  assert.match(shell, /browserOnly: processingMode === "browser"/);
  assert.match(shell, /const preservedData = data\.slice\(\)/);
  assert.match(shell, /sourceBytes: loaded\.data/);
  assert.match(shell, /assembleBrowserPdf/);
  assert.match(shell, /BROWSER_PDF_FIDELITY_WARNING/);
  assert.match(shell, /Copying and arranging original pages/);
  assert.doesNotMatch(shell, /function buildBrowserPdf\(pageOutputs\)/);
  assert.match(shell, /rasterizeBrowserPage\(page, sourceDocuments, preparedPage\)/);
  assert.match(shell, /if \(\/\^\(blob:\|data:\)\/i\.test\(downloadUrl\)\) return downloadUrl/);
  assert.match(shell, /if \(mode === "browser"\) setJob\(initialJob\)/);
  assert.match(shell, /Use Local agent/);
  assert.match(shell, /aria-disabled=\{processingMode === "browser"\}/);
  assert.match(shell, /Duplicate page\{processingMode === "browser" \? " · Local agent only" : ""\}/);
  assert.match(shell, /Browser mode accepts PDFs up to 50 MB total/);
  assert.doesNotMatch(shell, /pdf-browser-scope-note/);
  assert.match(shell, /LockKeyhole size=\{12\}/);
  assert.match(shell, /accept=\{processingMode === "browser" \? "image\/png,image\/jpeg,\.png,\.jpg,\.jpeg"/);
  assert.match(shell, /droppedFiles\.some\(\(file\) => isPdf\(file\)\)/);
  assert.doesNotMatch(shell, /Browser mode is temporarily unavailable/);
  assert.match(options, /\["Import existing PDFs", "Available", "Available"\]/);
  assert.match(options, /\["Merge existing PDFs", "Available", "Available"\]/);
  assert.match(options, /\["Duplicate page", "Available", "Local agent only", true\]/);
  assert.match(options, /\["Text boxes", "Available", "Local agent only", true\]/);
  assert.match(options, /\["Password-protected PDFs", "Available where supported", "Local agent only", true\]/);
  assert.match(options, /\["OCR and searchable text editing", "Available", "Local agent only", true\]/);
  assert.match(options, /\["Save to device and History", "Available", "Local agent only", true\]/);
  assert.match(options, /\["Browser image limit", "25 MB per image", "1 MB per image"\]/);
  assert.match(options, /\["Browser image formats", "PNG, JPG\/JPEG, HEIC\/HEIF, TIFF\/TIF, GIF, BMP", "PNG, JPG, JPEG only"\]/);
  assert.match(options, /\["Browser PDF total", "200 MB total", "50 MB total"\]/);
  assert.match(options, /processing-locked/);
});

test("PDF editor saves to the device in place without opening the export result view", async () => {
  const shell = await read("components/pdf-editor.jsx");
  const styles = await read("styles/globals.css");
  const toolSeoData = await read("lib/tool-seo-content.js");
  assert.match(shell, /const \[saveJob, setSaveJob\] = useState\(null\)/);
  assert.match(shell, /getProcessingJob\("local", saveJob\.id\)/);
  assert.match(shell, /setSaveJob\(\{ id: response\.jobId/);
  assert.match(shell, /setSaveJob\(null\);\s*setSaveNotice\(/);
  assert.match(shell, /without leaving the editor/);
  assert.match(toolSeoData, /⌘\/Ctrl\+S to save to the device/);
  assert.match(shell, /className="pdf-save-progress"/);
  assert.match(shell, /className=\{saveNotice\.type === "success" \? "success-banner pdf-save-notice"/);
  assert.match(shell, /className="pdf-retention-name"[\s\S]*ResultFilenameField/);
  assert.doesNotMatch(shell, /pdf-editor-toolbar-name/);
  assert.match(shell, /className="pdf-more-tools"/);
  const toolbarActions = shell.match(/<div className="pdf-editor-actions">([\s\S]*?)<\/div>\s*<\/div>\s*<input ref=\{pdfInputRef\}/)?.[1];
  assert.ok(toolbarActions, "PDF editor toolbar action placement could not be located");
  assert.match(toolbarActions, /pdf-more-tools/);
  assert.doesNotMatch(toolbarActions, /pdf-save-button/);
  const retentionStart = shell.indexOf('<div className="pdf-retention-row">');
  const toolbarStart = shell.indexOf('<div className={`pdf-editor-toolbar');
  assert.ok(retentionStart >= 0 && toolbarStart > retentionStart, "PDF retention row placement could not be located");
  const retentionRow = shell.slice(retentionStart, toolbarStart);
  assert.match(retentionRow, /Build your document/);
  assert.match(retentionRow, /pdf-save-button/);
  assert.match(shell.slice(toolbarStart), /pdf-editor-toolbar-tools-only/);
  assert.match(styles, /\.pdf-save-progress \{/);
  assert.match(styles, /\.pdf-save-notice \{/);
  assert.match(styles, /\.pdf-retention-name/);
  assert.doesNotMatch(styles, /\.pdf-more-tools-bottom/);
});

test("PDF result download route accepts a safe custom filename while preserving the extension", async () => {
  const route = await read("pages/api/jobs/[id]/download.js");
  const agent = await read("agent/server.js");
  assert.match(route, /requestedDownloadFilename\(request\.query\.filename, result\.filename\)/);
  assert.match(agent, /requestedDownloadName\(requestedFilename, result\.filename/);
  assert.match(agent, /url\.searchParams\.get\("filename"\)/);
});
