import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { FREE_ACCESS_CODE, FREE_ACCESS_CODE_LIFETIME_MS, FREE_ACCESS_DURATION_MS, FREE_ACCESS_REDEMPTION_WINDOW_MS } from "../lib/free-access.js";
import { AUTHOR_EMAIL, AUTHOR_ID, AUTHOR_NAME, metadataForPathname, PRODUCT_NAME, PRODUCT_TAGLINE, PUBLIC_ROUTES, SITE_URL } from "../lib/site-metadata.js";

const projectDirectory = path.resolve(new URL("..", import.meta.url).pathname);

async function read(relativePath) {
  return fs.readFile(path.join(projectDirectory, relativePath), "utf8");
}

test("public site surfaces have legal links and SEO metadata", async () => {
  const app = await read("pages/_app.jsx");
  const document = await read("pages/_document.jsx");
  const shell = await read("components/app-shell.jsx");
  const toolPage = await read("components/tool-page.jsx");
  const pdfEditor = await read("components/pdf-editor.jsx");
  const pdfTextEditor = await read("components/pdf-text-editor.jsx");
  const localAgent = await read("components/local-agent-setup.jsx");
  const toolSeo = await read("components/tool-seo-content.jsx");
  const toolSeoData = await read("lib/tool-seo-content.js");
  const footer = await read("components/app-footer.jsx");
  const seo = await read("components/seo-head.jsx");
  const processingMode = await read("components/processing-mode.jsx");
  const history = await read("components/tool-history.jsx");
  const privacy = await read("pages/privacy.jsx");
  const terms = await read("pages/terms.jsx");
  const contact = await read("pages/contact.jsx");
  const home = await read("pages/index.jsx");
  const freeAccessModal = await read("components/free-access-modal.jsx");
  const styles = await read("styles/globals.css");

  assert.match(app, /SeoHead/);
  assert.match(document, /<Html lang="en">/);
  assert.match(document, /name="theme-color"/);
  assert.match(document, /media-toolbox-theme/);
  assert.match(document, /document\.documentElement\.dataset\.theme/);
  assert.match(styles, /\[data-theme="dark"\] \.section-kicker \{ color: #8fe0d8; \}/);
  assert.match(styles, /\[data-theme="dark"\] \.tool-nav-item \{ color: #aabccc; \}/);
  assert.match(shell, /AppFooter/);
  assert.match(shell, /<Link href="\/" title="Home">Home<\/Link>/);
  assert.match(shell, /<Link href="\/" className="topbar-brand" aria-label="NativeMedia Agent home">/);
  assert.ok(shell.indexOf('href: "/local-agent"') < shell.indexOf('href: "/image-converter"'), "Local agent should be the first hamburger navigation item");
  assert.match(shell, /<img className="brand-logo" src="\/media-toolbox-logo\.png" alt="NativeMedia Agent logo" title="NativeMedia Agent" \/>/);
  assert.match(shell, /<\/nav>\n      <button className="sidebar-menu-button"/);
  assert.match(shell, /<div className="brand-copy"><span>NativeMedia<\/span><strong>Agent<\/strong><\/div>/);
  assert.match(shell, /PRODUCT_TAGLINE/);
  assert.match(shell, /useState\("dark"\)/);
  assert.match(shell, /savedTheme === "light" \? "light" : "dark"/);
  assert.match(footer, /href="\/privacy" title="Privacy Policy"/);
  assert.match(footer, /href="\/terms" title="Terms and Conditions"/);
  assert.match(footer, /href="\/contact" title="Contact Us"/);
  assert.match(footer, /href="\/sitemap\.xml" title="Sitemap"/);
  assert.match(footer, /href="\/privacy"/);
  assert.match(footer, /href="\/terms"/);
  assert.match(footer, /href="\/sitemap\.xml"/);
  assert.match(footer, /app-footer-copyright/);
  assert.match(footer, /© 2026 \{PRODUCT_NAME\}\. All rights reserved\./u);
  assert.match(seo, /meta name="description"/);
  assert.match(seo, /meta name="author" content=\{AUTHOR_NAME\}/);
  assert.match(seo, /meta name="publisher" content=\{PRODUCT_NAME\}/);
  assert.match(seo, /meta name="googlebot"/);
  assert.match(seo, /link rel="canonical"/);
  assert.match(seo, /link rel="icon" type="image\/png" href="\/media-toolbox-logo\.png"/);
  assert.match(seo, /link rel="apple-touch-icon" href="\/media-toolbox-logo\.png"/);
  assert.match(seo, /property="og:title"/);
  assert.match(seo, /property="og:image"/);
  assert.match(seo, /name="twitter:card"/);
  assert.match(seo, /application\/ld\+json/);
  assert.match(seo, /"@graph"/);
  assert.match(seo, /"@type": "Person"/);
  assert.match(seo, /"@id": AUTHOR_ID/);
  assert.match(seo, /founder: \{ "@id": AUTHOR_ID \}/);
  assert.match(seo, /contactPoint:/);
  assert.match(seo, /author: \{ "@id": AUTHOR_ID \}/);
  assert.match(seo, /publisher: \{ "@id": `\$\{SITE_URL\}#organization` \}/);
  assert.match(seo, /email: AUTHOR_EMAIL/);
  assert.match(seo, /"@type": "WebSite"/);
  assert.match(seo, /"@type": \["WebApplication", "SoftwareApplication"\]/);
  assert.match(seo, /"@type": "BreadcrumbList"/);
  assert.match(seo, /"@type": "FAQPage"/);
  assert.match(seo, /price: "0"/);
  assert.doesNotMatch(shell, /ToolSeoContent/);
  assert.match(history, /Helpful guide/);
  assert.match(toolPage, /activeView === "guide"/);
  assert.match(toolPage, /ToolSeoContent pathname=\{`\/\$\{tool\}`\}/);
  assert.match(toolPage, /ToolFaqContent pathname=\{`\/\$\{tool\}`\}/);
  assert.match(pdfEditor, /activeView === "guide" \? <ToolSeoContent pathname="\/pdf-editor" \/>/);
  assert.match(pdfEditor, /ToolFaqContent pathname="\/pdf-editor" \/>/);
  assert.match(pdfTextEditor, /activeView === "guide" \? <ToolSeoContent pathname="\/pdf-text-editor" \/>/);
  assert.match(pdfTextEditor, /ToolFaqContent pathname="\/pdf-text-editor" \/>/);
  assert.match(localAgent, /ToolFaqContent pathname="\/local-agent" \/>/);
  assert.match(shell, /Breadcrumbs pathname=\{pathname\}/);
  assert.match(shell, /Temporary data follows cleanup rules; local results are kept only when you choose\./);
  assert.doesNotMatch(shell, /Files are temporary and auto-cleaned\./);
  assert.match(shell, /MOBILE_NOTICE_KEY/);
  assert.match(shell, /Mobile support is currently in progress/);
  assert.match(shell, /role="alert"/);
  assert.match(shell, /window\.matchMedia\("\(max-width: 680px\)"\)/);
  assert.match(processingMode, /const serverAvailable = Boolean\(locations\?\.server\?\.available && \(locations\?\.server\?\.connected \|\| locations\?\.server\?\.ready\)\);/);
  assert.match(processingMode, /const modes = \["local", \.\.\.\(serverAvailable \? \["server"\] : \[\]\)\];/);
  assert.match(processingMode, /Local agent \+ server/);
  assert.doesNotMatch(history, /server/i);
  assert.match(toolSeo, /Frequently asked questions/);
  assert.match(toolSeo, /export function ToolFaqContent/);
  assert.match(toolSeo, /useState\(0\)/);
  assert.match(toolSeo, /aria-expanded=\{openFaqIndex === index\}/);
  assert.match(toolSeo, /tool-seo-faq-question/);
  assert.match(toolSeo, /ChevronDown/);
  assert.match(toolSeo, /openFaqIndex === index &&/);
  assert.match(toolSeo, /Privacy and file safety/);
  assert.match(toolSeoData, /"Which image formats are supported\?"/);
  assert.match(toolSeoData, /"Can every damaged video be repaired\?"/);
  assert.match(toolSeoData, /"Which keyboard shortcuts are available\?"/);
  assert.match(toolSeoData, /Image processing currently runs through the Local agent/);
  assert.doesNotMatch(toolSeoData, /Server mode|server worker|Server uploads/);
  assert.match(toolSeoData, /the licensing service does not receive media files/);
  assert.doesNotMatch(toolSeoData, /The editor supports up to five PDFs with a combined 200 MB limit/);
  assert.match(home, /Understand retention/);
  assert.match(home, /Private PDF and media tools for your desktop/);
  assert.match(home, /href="\/pdf-editor"/);
  assert.match(home, /href="\/image-converter"/);
  assert.match(home, /href: "\/svg-to-png", label: "SVG to PNG"/);
  assert.match(home, /Rasterize SVG files at 1×, 2×, 3×, 4×, or custom dimensions/);
  assert.doesNotMatch(home, /category: "Private processing"/);
  assert.doesNotMatch(home, /label: "Local agent"/);
  assert.match(home, /Process files on your computer/);
  assert.match(home, /processes files locally on your Mac, Windows, or Linux computer/);
  assert.doesNotMatch(home, /browser where supported/);
  assert.match(home, /Choose the tool for your file/);
  assert.match(freeAccessModal, /FREE_ACCESS_CODE/);
  assert.match(freeAccessModal, /media_toolbox_free_access_seen/);
  assert.match(freeAccessModal, /window\.addEventListener\("scroll", showOnScroll, \{ passive: true \}\)/);
  assert.match(freeAccessModal, /window\.scrollY <= 0/);
  assert.doesNotMatch(freeAccessModal, /5000/);
  assert.match(freeAccessModal, /Copy code/);
  assert.match(freeAccessModal, /Maybe later/);
  assert.match(freeAccessModal, /free-access-celebration/);
  assert.match(freeAccessModal, /🎉/u);
  assert.match(freeAccessModal, /free until \{expiryText\}/);
  assert.match(freeAccessModal, /\/api\/license\/v1\/free-access/);
  assert.doesNotMatch(freeAccessModal, /Try \{PRODUCT_NAME\} free for 7 days/);
  assert.match(freeAccessModal, /document\.cookie/);
  assert.match(styles, /\.free-access-backdrop \{ position: fixed/);
  assert.equal(FREE_ACCESS_DURATION_MS, 7 * 24 * 60 * 60 * 1000);
  assert.equal(FREE_ACCESS_CODE_LIFETIME_MS, 90 * 24 * 60 * 60 * 1000);
  assert.equal(FREE_ACCESS_REDEMPTION_WINDOW_MS, 60 * 24 * 60 * 60 * 1000);
  assert.match(privacy, /Privacy Policy/);
  assert.match(privacy, /\{PRODUCT_NAME\} is operated by Aman Gupta/);
  assert.match(privacy, /mailto:a20000\.gupta@gmail\.com/);
  assert.doesNotMatch(privacy, /server jobs|server mode|configured server/i);
  assert.match(privacy, /Files and results/);
  assert.match(terms, /Terms and Conditions/);
  assert.match(terms, /\{PRODUCT_NAME\} is operated by Aman Gupta/);
  assert.match(terms, /mailto:a20000\.gupta@gmail\.com/);
  assert.match(terms, /Local agent and licensing/);
  assert.match(contact, /<h1>Contact Us<\/h1>/);
  assert.match(contact, /getMonthStartIso/);
  assert.match(contact, /getServerSideProps/);
  assert.match(contact, /Last updated:/);
  assert.match(contact, /mailto:\$\{AUTHOR_EMAIL\}/);
  assert.match(contact, /\{PRODUCT_NAME\} is operated by \{AUTHOR_NAME\}/);
  assert.match(styles, /\.app-footer \{/);
  assert.match(styles, /\.main-area \{[^}]*min-height: 100vh[^}]*display: flex[^}]*flex-direction: column/);
  assert.match(styles, /\.app-footer \{[^}]*margin: auto auto 0/);
  assert.match(styles, /\.sidebar-menu-button \{[^}]*margin: auto 8px 19px 0/);
  assert.match(styles, /\.legal-document \{/);
  assert.match(styles, /\.mobile-support-notice \{ position: fixed/);
});

test("sitemap and robots routes expose only public pages", async () => {
  const sitemap = await read("pages/sitemap.xml.js");
  const robots = await read("pages/robots.txt.js");

  assert.match(sitemap, /Content-Type.*application\/xml/);
  assert.match(sitemap, /PUBLIC_ROUTES/);
  assert.match(sitemap, /getServerSideProps/);
  assert.match(robots, /Disallow: \/admin/);
  assert.match(robots, /Disallow: \/api\//);
  assert.match(robots, /sitemap\.xml/);
  assert.ok(!PUBLIC_ROUTES.some(({ path: route }) => route.startsWith("/admin") || route.startsWith("/api")));
  assert.ok(PUBLIC_ROUTES.some(({ path: route }) => route === "/"));
  assert.ok(PUBLIC_ROUTES.some(({ path: route }) => route === "/privacy"));
  assert.ok(PUBLIC_ROUTES.some(({ path: route }) => route === "/terms"));
  assert.ok(PUBLIC_ROUTES.some(({ path: route }) => route === "/contact"));
  assert.equal(SITE_URL, "https://native-media-agent.vercel.app");
});

test("SEO metadata is route-specific and normalizes query strings", () => {
  assert.equal(AUTHOR_NAME, "Aman Gupta");
  assert.equal(AUTHOR_EMAIL, "a20000.gupta@gmail.com");
  assert.equal(PRODUCT_NAME, "NativeMedia Agent");
  assert.equal(PRODUCT_TAGLINE, "Your browser interface. Your computer does the work.");
  assert.equal(AUTHOR_ID, `${SITE_URL}#author`);
  assert.equal(metadataForPathname("/pdf-editor?tab=history").title, "Desktop PDF Editor | NativeMedia Agent");
  assert.equal(metadataForPathname("/privacy/").title, "Privacy Policy | NativeMedia Agent");
  assert.equal(metadataForPathname("/contact/").title, "Contact Us | NativeMedia Agent");
  assert.equal(metadataForPathname("/").title, "Private Desktop PDF & Media Tools | NativeMedia Agent");
  assert.equal(metadataForPathname("/unknown").title, "Private Desktop PDF & Media Tools | NativeMedia Agent");
  assert.equal(metadataForPathname("/admin").noIndex, true);
  assert.equal(metadataForPathname("/license-admin").noIndex, true);
});

test("indexable page descriptions are useful and within the recommended range", () => {
  const indexableRoutes = ["/", ...PUBLIC_ROUTES.filter(({ path: route }) => route !== "/" && !metadataForPathname(route).noIndex).map(({ path: route }) => route)];
  for (const route of indexableRoutes) {
    const description = metadataForPathname(route).description;
    assert.ok(description.length >= 120 && description.length <= 320, `${route} description length was ${description.length}`);
  }
});
